// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SECRET_TYPE int32

const (
	SECRET_TYPE_CREDENTIALS SECRET_TYPE = 0
	SECRET_TYPE_TEXT        SECRET_TYPE = 1
	SECRET_TYPE_BINARY      SECRET_TYPE = 2
	SECRET_TYPE_CARD        SECRET_TYPE = 3
)

// Enum value maps for SECRET_TYPE.
var (
	SECRET_TYPE_name = map[int32]string{
		0: "CREDENTIALS",
		1: "TEXT",
		2: "BINARY",
		3: "CARD",
	}
	SECRET_TYPE_value = map[string]int32{
		"CREDENTIALS": 0,
		"TEXT":        1,
		"BINARY":      2,
		"CARD":        3,
	}
)

func (x SECRET_TYPE) Enum() *SECRET_TYPE {
	p := new(SECRET_TYPE)
	*p = x
	return p
}

func (x SECRET_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SECRET_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (SECRET_TYPE) Type() protoreflect.EnumType {
	return &file_gophkeeper_proto_enumTypes[0]
}

func (x SECRET_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SECRET_TYPE.Descriptor instead.
func (SECRET_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type EVENT_TYPE int32

const (
	EVENT_TYPE_PASSWORD_CHANGE EVENT_TYPE = 0
	EVENT_TYPE_SECRET_ADD      EVENT_TYPE = 1
	EVENT_TYPE_SECRET_DELETE   EVENT_TYPE = 2
	EVENT_TYPE_SECRET_UPDATE   EVENT_TYPE = 3
)

// Enum value maps for EVENT_TYPE.
var (
	EVENT_TYPE_name = map[int32]string{
		0: "PASSWORD_CHANGE",
		1: "SECRET_ADD",
		2: "SECRET_DELETE",
		3: "SECRET_UPDATE",
	}
	EVENT_TYPE_value = map[string]int32{
		"PASSWORD_CHANGE": 0,
		"SECRET_ADD":      1,
		"SECRET_DELETE":   2,
		"SECRET_UPDATE":   3,
	}
)

func (x EVENT_TYPE) Enum() *EVENT_TYPE {
	p := new(EVENT_TYPE)
	*p = x
	return p
}

func (x EVENT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EVENT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_proto_enumTypes[1].Descriptor()
}

func (EVENT_TYPE) Type() protoreflect.EnumType {
	return &file_gophkeeper_proto_enumTypes[1]
}

func (x EVENT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EVENT_TYPE.Descriptor instead.
func (EVENT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{1}
}

type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *Name) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AuthMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthMeta) Reset() {
	*x = AuthMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMeta) ProtoMessage() {}

func (x *AuthMeta) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMeta.ProtoReflect.Descriptor instead.
func (*AuthMeta) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMeta) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthMeta) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash string `protobuf:"bytes,3,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	Timestamp    int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SecretSyncData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretID  string `protobuf:"bytes,1,opt,name=secretID,proto3" json:"secretID,omitempty"`
	Hash      string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SecretSyncData) Reset() {
	*x = SecretSyncData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretSyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSyncData) ProtoMessage() {}

func (x *SecretSyncData) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSyncData.ProtoReflect.Descriptor instead.
func (*SecretSyncData) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *SecretSyncData) GetSecretID() string {
	if x != nil {
		return x.SecretID
	}
	return ""
}

func (x *SecretSyncData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SecretSyncData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetSecretsSyncDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*SecretSyncData `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetSecretsSyncDataResponse) Reset() {
	*x = GetSecretsSyncDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecretsSyncDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsSyncDataResponse) ProtoMessage() {}

func (x *GetSecretsSyncDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsSyncDataResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsSyncDataResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *GetSecretsSyncDataResponse) GetItems() []*SecretSyncData {
	if x != nil {
		return x.Items
	}
	return nil
}

type EncodedSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner            int64       `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Description      string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type             SECRET_TYPE `protobuf:"varint,5,opt,name=type,proto3,enum=proto.SECRET_TYPE" json:"type,omitempty"`
	EncData          []byte      `protobuf:"bytes,6,opt,name=encData,proto3" json:"encData,omitempty"`
	Hash             string      `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
	DateLastModified int64       `protobuf:"varint,8,opt,name=date_last_modified,json=dateLastModified,proto3" json:"date_last_modified,omitempty"`
}

func (x *EncodedSecret) Reset() {
	*x = EncodedSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedSecret) ProtoMessage() {}

func (x *EncodedSecret) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedSecret.ProtoReflect.Descriptor instead.
func (*EncodedSecret) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *EncodedSecret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EncodedSecret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EncodedSecret) GetOwner() int64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *EncodedSecret) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EncodedSecret) GetType() SECRET_TYPE {
	if x != nil {
		return x.Type
	}
	return SECRET_TYPE_CREDENTIALS
}

func (x *EncodedSecret) GetEncData() []byte {
	if x != nil {
		return x.EncData
	}
	return nil
}

func (x *EncodedSecret) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EncodedSecret) GetDateLastModified() int64 {
	if x != nil {
		return x.DateLastModified
	}
	return 0
}

type SecretID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretID string `protobuf:"bytes,1,opt,name=secretID,proto3" json:"secretID,omitempty"`
}

func (x *SecretID) Reset() {
	*x = SecretID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretID) ProtoMessage() {}

func (x *SecretID) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretID.ProtoReflect.Descriptor instead.
func (*SecretID) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *SecretID) GetSecretID() string {
	if x != nil {
		return x.SecretID
	}
	return ""
}

type ChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type EVENT_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EVENT_TYPE" json:"type,omitempty"`
	// Types that are assignable to Payload:
	//	*ChangeEvent_SecretItem
	//	*ChangeEvent_Id
	//	*ChangeEvent_String_
	Payload isChangeEvent_Payload `protobuf_oneof:"payload"`
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gophkeeper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeEvent) GetType() EVENT_TYPE {
	if x != nil {
		return x.Type
	}
	return EVENT_TYPE_PASSWORD_CHANGE
}

func (m *ChangeEvent) GetPayload() isChangeEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ChangeEvent) GetSecretItem() *EncodedSecret {
	if x, ok := x.GetPayload().(*ChangeEvent_SecretItem); ok {
		return x.SecretItem
	}
	return nil
}

func (x *ChangeEvent) GetId() int64 {
	if x, ok := x.GetPayload().(*ChangeEvent_Id); ok {
		return x.Id
	}
	return 0
}

func (x *ChangeEvent) GetString_() string {
	if x, ok := x.GetPayload().(*ChangeEvent_String_); ok {
		return x.String_
	}
	return ""
}

type isChangeEvent_Payload interface {
	isChangeEvent_Payload()
}

type ChangeEvent_SecretItem struct {
	SecretItem *EncodedSecret `protobuf:"bytes,2,opt,name=secretItem,proto3,oneof"`
}

type ChangeEvent_Id struct {
	Id int64 `protobuf:"varint,3,opt,name=id,proto3,oneof"`
}

type ChangeEvent_String_ struct {
	String_ string `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

func (*ChangeEvent_SecretItem) isChangeEvent_Payload() {}

func (*ChangeEvent_Id) isChangeEvent_Payload() {}

func (*ChangeEvent_String_) isChangeEvent_Payload() {}

var File_gophkeeper_proto protoreflect.FileDescriptor

var file_gophkeeper_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1a, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x74, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5e, 0x0a, 0x0e,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x49, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xef, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x45, 0x43, 0x52,
	0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x65, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x73,
	0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x26, 0x0a, 0x08, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49,
	0x44, 0x22, 0xa3, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x3e, 0x0a, 0x0b, 0x53, 0x45, 0x43, 0x52, 0x45,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4e,
	0x54, 0x49, 0x41, 0x4c, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x03, 0x2a, 0x57, 0x0a, 0x0a, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52,
	0x44, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45,
	0x43, 0x52, 0x45, 0x54, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45,
	0x43, 0x52, 0x45, 0x54, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x03,
	0x32, 0xed, 0x03, 0x0a, 0x0a, 0x47, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12,
	0x2c, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x1a, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x2f, 0x0a,
	0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x1a, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x4e,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x4d,
	0x65, 0x74, 0x61, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x53, 0x79,
	0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x4d,
	0x65, 0x74, 0x61, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x44, 0x1a, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x41, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x41, 0x0a,
	0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x70, 0x6f, 0x6c, 0x73, 0x68, 0x2f, 0x79, 0x61, 0x70, 0x72, 0x2d, 0x67, 0x6f, 0x70, 0x68, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_proto_rawDescData = file_gophkeeper_proto_rawDesc
)

func file_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_gophkeeper_proto_rawDescData)
	})
	return file_gophkeeper_proto_rawDescData
}

var file_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gophkeeper_proto_goTypes = []interface{}{
	(SECRET_TYPE)(0),                   // 0: proto.SECRET_TYPE
	(EVENT_TYPE)(0),                    // 1: proto.EVENT_TYPE
	(*Credentials)(nil),                // 2: proto.Credentials
	(*Name)(nil),                       // 3: proto.Name
	(*AuthMeta)(nil),                   // 4: proto.AuthMeta
	(*User)(nil),                       // 5: proto.User
	(*SecretSyncData)(nil),             // 6: proto.SecretSyncData
	(*GetSecretsSyncDataResponse)(nil), // 7: proto.GetSecretsSyncDataResponse
	(*EncodedSecret)(nil),              // 8: proto.EncodedSecret
	(*SecretID)(nil),                   // 9: proto.SecretID
	(*ChangeEvent)(nil),                // 10: proto.ChangeEvent
	(*emptypb.Empty)(nil),              // 11: google.protobuf.Empty
}
var file_gophkeeper_proto_depIdxs = []int32{
	5,  // 0: proto.AuthMeta.user:type_name -> proto.User
	6,  // 1: proto.GetSecretsSyncDataResponse.items:type_name -> proto.SecretSyncData
	0,  // 2: proto.EncodedSecret.type:type_name -> proto.SECRET_TYPE
	1,  // 3: proto.ChangeEvent.type:type_name -> proto.EVENT_TYPE
	8,  // 4: proto.ChangeEvent.secretItem:type_name -> proto.EncodedSecret
	2,  // 5: proto.Gophkeeper.Login:input_type -> proto.Credentials
	2,  // 6: proto.Gophkeeper.Register:input_type -> proto.Credentials
	11, // 7: proto.Gophkeeper.GetSecretSyncMeta:input_type -> google.protobuf.Empty
	3,  // 8: proto.Gophkeeper.GetSecretSyncMetaByName:input_type -> proto.Name
	9,  // 9: proto.Gophkeeper.GetSecret:input_type -> proto.SecretID
	8,  // 10: proto.Gophkeeper.SaveEncodedSecret:input_type -> proto.EncodedSecret
	9,  // 11: proto.Gophkeeper.DeleteSecret:input_type -> proto.SecretID
	11, // 12: proto.Gophkeeper.SubscribeOnChange:input_type -> google.protobuf.Empty
	4,  // 13: proto.Gophkeeper.Login:output_type -> proto.AuthMeta
	4,  // 14: proto.Gophkeeper.Register:output_type -> proto.AuthMeta
	7,  // 15: proto.Gophkeeper.GetSecretSyncMeta:output_type -> proto.GetSecretsSyncDataResponse
	6,  // 16: proto.Gophkeeper.GetSecretSyncMetaByName:output_type -> proto.SecretSyncData
	8,  // 17: proto.Gophkeeper.GetSecret:output_type -> proto.EncodedSecret
	11, // 18: proto.Gophkeeper.SaveEncodedSecret:output_type -> google.protobuf.Empty
	11, // 19: proto.Gophkeeper.DeleteSecret:output_type -> google.protobuf.Empty
	10, // 20: proto.Gophkeeper.SubscribeOnChange:output_type -> proto.ChangeEvent
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gophkeeper_proto_init() }
func file_gophkeeper_proto_init() {
	if File_gophkeeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gophkeeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretSyncData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecretsSyncDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gophkeeper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gophkeeper_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ChangeEvent_SecretItem)(nil),
		(*ChangeEvent_Id)(nil),
		(*ChangeEvent_String_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gophkeeper_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_proto_depIdxs,
		EnumInfos:         file_gophkeeper_proto_enumTypes,
		MessageInfos:      file_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_proto = out.File
	file_gophkeeper_proto_rawDesc = nil
	file_gophkeeper_proto_goTypes = nil
	file_gophkeeper_proto_depIdxs = nil
}
